[app]
# (str) Title of your application
title = Calculator

# (str) Package name
package.name = system_calc_v4

# (str) Package domain (needed for android packaging)
package.domain = org.sovereign.tools

# (str) Source code where the main.py lives
source.dir = .

# (list) Source files to include (including the icon we manifest in YAML)
source.include_exts = py,png,jpg,kv,atlas,db

# (str) Application versioning
version = 4.8

# (list) Application requirements
# Pinned Cython and Kivy for 13579 stability
requirements = python3,kivy==2.3.0,hostpython3,android,sqlite3,cython==0.29.33

# (str) Supported orientation
orientation = portrait

# (bool) Indicate if the application should be fullscreen
fullscreen = 1

# (list) Permissions
android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE

# (list) Architecture Strike
# Pinned to arm64-v8a to prevent runner memory timeouts
android.archs = arm64-v8a

# (str) Icon filename (Generated by the YAML strike)
icon.filename = calc_icon.png

# (int) Android API to use
android.api = 31

# (int) Minimum API required
android.minapi = 21

# (str) Android NDK version (CRITICAL: Must be 25b to match Kivy 2.3.0)
android.ndk = 25b

# (bool) Accept the SDK license automatically
android.accept_sdk_license = True

# (str) Android logcat filters
android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a symbolic link
android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = arm64-v8a

[buildozer]
# (int) Log level (2 = high intensity detail)
log_level = 2

# (int) Display warning if buildozer is run as root (1 = True)
warn_on_root = 1
